<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic emessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Add User' => '添加用户',
  'All' => '所有',
  'Change Password' => '更改密码',
  'Close' => '关闭',
  'Comfirm' => '确认',
  'Delete User' => '删除用户',
  'Department' => '部门',
  'Departments' => '部门',
  'Email' => '邮箱',
  'Logout' => '退出',
  'Mobie Phone' => '手机',
  'Module Management' => '模块管理',
  'Name' => '姓名',
  'New Password' => '新密码',
  'Old Password' => '旧密码',
  'Password' => '密码',
  'Please sign in' => '请登录',
  'Position' => '职位',
  'Positions' => '职位',
  'Refresh List' => '刷新列表',
  'Retype New Password' => '确认新密码',
  'Role' => '角色',
  'Roles' => '角色',
  'Save' => '保存',
  'Search' => '',
  'Server error, initialize main UI fail!' => '服务器出错！界面初始化失败！',
  'Server error, please contact administrator!' => '服务器出错！请联系系统管理员！',
  'Sign in' => '登录',
  'Signing in' => '登录中',
  'User' => '用户',
  'User Management' => '用户管理',
  'User Name' => '用户名',
  'User name or password invalid' => '用户名或密码不正确',
  'Users' => '用户',
  'Work Phone' => '电话',
);
